version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-checks-and-test:
    executor: python/default
    steps:
      - checkout
      - make install
      - run:
          command: make checks && make test
          name: Test

workflows:
  main:
    jobs:
      - build-and-checks-and-test
